name: Pull Request CD

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Deploy application
        if: github.ref != 'refs/heads/master'
        run: |
          if [ "${{ secrets.NOW_TOKEN }}" != "" ]; then
            npx now --token ${{ secrets.NOW_TOKEN }}
          fi
